---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: gp2
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: px-repl1
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "1"
allowVolumeExpansion: true
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: px-repl3
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "3"
allowVolumeExpansion: true